//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDBFRaceFlow.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UDBFRaceFlow.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races from this category {0} don`t have enough interval between rest races.
        /// </summary>
        public static string Error_CheckIntervalFail {
            get {
                return ResourceManager.GetString("Error CheckIntervalFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race 1 must be earlier than Race 2.
        /// </summary>
        public static string Error_Chronological {
            get {
                return ResourceManager.GetString("Error Chronological", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semifinal or Final should be single.
        /// </summary>
        public static string Error_CountOfRaces {
            get {
                return ResourceManager.GetString("Error CountOfRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} with Id {1} not found.
        /// </summary>
        public static string Error_EntityWithIdNotFound {
            get {
                return ResourceManager.GetString("Error EntityWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane {0} is empty.
        /// </summary>
        public static string Error_LaneIsNull {
            get {
                return ResourceManager.GetString("Error LaneIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} cannot be greater than {ComparisonValue}..
        /// </summary>
        public static string Error_MaxLength {
            get {
                return ResourceManager.GetString("Error MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} not found.
        /// </summary>
        public static string Error_MethodNotFound {
            get {
                return ResourceManager.GetString("Error MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} cannot be less than {ComparisonValue}..
        /// </summary>
        public static string Error_MinLength {
            get {
                return ResourceManager.GetString("Error MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Enough Heat Results for build Semifinal.
        /// </summary>
        public static string Error_NotEnoughHeatResults {
            get {
                return ResourceManager.GetString("Error NotEnoughHeatResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Enough Semifinal Results for build Final.
        /// </summary>
        public static string Error_NotEnoughSemisResults {
            get {
                return ResourceManager.GetString("Error NotEnoughSemisResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of teams not enough to build system.
        /// </summary>
        public static string Error_NotEnoughTeam {
            get {
                return ResourceManager.GetString("Error NotEnoughTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {PropertyName} is Required.
        /// </summary>
        public static string Error_PropertyIsRequired {
            get {
                return ResourceManager.GetString("Error PropertyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} must be unique.
        /// </summary>
        public static string Error_PropertyNotUnique {
            get {
                return ResourceManager.GetString("Error PropertyNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} property should be equal {1}.
        /// </summary>
        public static string Error_PropertyShouldBeEqual {
            get {
                return ResourceManager.GetString("Error PropertyShouldBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race {0} is null.
        /// </summary>
        public static string Error_RaceIsNull {
            get {
                return ResourceManager.GetString("Error RaceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app don`t have a rule for this distance {0}.
        /// </summary>
        public static string Error_UnknownDistance {
            get {
                return ResourceManager.GetString("Error UnknownDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation for {0} failed with errors: {0}.
        /// </summary>
        public static string Error_ValidationFailed {
            get {
                return ResourceManager.GetString("Error ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid for category {0} successfully generated.
        /// </summary>
        public static string Info_FinishGenerateGrid {
            get {
                return ResourceManager.GetString("Info FinishGenerateGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} build. Lane 1: Team {1}. Lane 2: Team {2}. Lane 3: Team {3}. Lane 4: Team {4}. .
        /// </summary>
        public static string Info_RaceWasBuilded {
            get {
                return ResourceManager.GetString("Info RaceWasBuilded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of building race {0} for category {1}.
        /// </summary>
        public static string Info_StartBuildRace {
            get {
                return ResourceManager.GetString("Info StartBuildRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start generating grid for category {0}.
        /// </summary>
        public static string Info_StartGeneratingGrid {
            get {
                return ResourceManager.GetString("Info StartGeneratingGrid", resourceCulture);
            }
        }
    }
}
