// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UDBFRaceFlow.Infrastructure.Persistence;

#nullable disable

namespace UDBFRaceFlow.Infrastructure.Migrations
{
    [DbContext(typeof(RaceDbContext))]
    [Migration("20260515114945_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UDBFRaceFlow.Domain.Entities.Race.RaceData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoatSize")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("Distance")
                        .HasColumnType("integer");

                    b.Property<int>("GenderCategory")
                        .HasColumnType("integer");

                    b.Property<int>("RaceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RaceStatus")
                        .HasColumnType("integer");

                    b.Property<int>("RaceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaceNumber")
                        .IsUnique();

                    b.ToTable("Races");
                });

            modelBuilder.Entity("UDBFRaceFlow.Domain.Entities.Race.RaceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FinishPlace")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("FinishTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("StartLane")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("TeamId");

                    b.ToTable("RaceEntries");
                });

            modelBuilder.Entity("UDBFRaceFlow.Domain.Entities.Team.TeamData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("UDBFRaceFlow.Domain.Entities.Race.RaceEntry", b =>
                {
                    b.HasOne("UDBFRaceFlow.Domain.Entities.Race.RaceData", "Race")
                        .WithMany("RaceEntries")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UDBFRaceFlow.Domain.Entities.Team.TeamData", "Team")
                        .WithMany("RaceEntries")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("UDBFRaceFlow.Domain.Entities.Race.RaceData", b =>
                {
                    b.Navigation("RaceEntries");
                });

            modelBuilder.Entity("UDBFRaceFlow.Domain.Entities.Team.TeamData", b =>
                {
                    b.Navigation("RaceEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
